language: node_js
matrix:
  include:
    - node_js: "7"
      env: TEST=all
    - node_js: "6"
      env: TEST=all
    - node_js: "5"
      env: TEST=all
    - node_js: "4"
      env: TEST=all
    - node_js: "0.12"
      env: TEST=test
    - node_js: "0.10"
      env: TEST=test
    - node_js: "iojs"
      env: TEST=test
  fast_finish: true
script:
  - npm run "$TEST"
after_success: 'npm run coveralls'
